### PR TITLE
fix: update npm packages to fix security alerts

### PR DESCRIPTION
**Pull request by DanielBadan**

### CODE REVIEW

**Comment by DanielBadan** [comment]
Sure, I forked it on my own profile.

**Comment by alexander-akait** [comment]
@danielverejan thanks! Please also update README with link on new repo, ping me when you do it :+1:

**Comment by DanielBadan** [comment]
@evilebottnawi all done

**Comment by alexander-akait** [comment]
@danielverejan don't see link in README

**Comment by DanielBadan** [comment]
@evilebottnawi sorry I'm a bit confused,
I've added a link to the new repo in README, current repo, master branch.
Do I need to add it somewhere else?

**Comment by alexander-akait** [comment]
@danielverejan oh, i see thanks

**Pull request merged**
